name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Changed from ubuntu to windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.0"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Server
        run: |
          echo "Deploying application..."
          # Add your actual deployment commands here
          # Example: python deploy_script.py
          docker build -t myapp .
          docker run -d -p 5000:5000 myapp

