name: CI Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Running on Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.0"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium webdriver-manager

      - name: Start FastAPI Server
        run: |
          Start-Process -NoNewWindow -FilePath "python" -ArgumentList "backend.py"
        shell: powershell

      - name: Wait for FastAPI Server
        shell: powershell
        run: |
          $retries = 10
          $delay = 5
          for ($i = 0; $i -lt $retries; $i++) {
              try {
                  Invoke-WebRequest -Uri "http://127.0.0.1:8000/docs" -UseBasicParsing
                  Write-Host "✅ FastAPI server is up!"
                  exit 0
              } catch {
                  Write-Host "⏳ FastAPI server not available yet. Retrying in $delay seconds..."
                  Start-Sleep -Seconds $delay
              }
          }
          Write-Host "❌ FastAPI server failed to start."
          exit 1

      - name: Run pytest tests
        run: pytest -v testing_with_pytest.py
      
      - name: Run unittest tests
        run: python testing_with_unittest.py

      - name: Run Selenium tests
        run: python selenium_test.py
